[workspace]
resolver = "2"
members = ["archival", "eh_bot", "help", "regex_macro", "reminders", "utils", "wiper"]
default-members = ["eh_bot"]

[workspace.dependencies]
anyhow = "1.0"
camino = "1.2.6"
chrono = "0.4"
fs-err = "3.3.1"
futures = "0.3"
fuzzydate = "0.4.1"
humantime = "2.4.0"
indexmap = "2.14.2"
itertools = "0.15.0"
lazy-regex = "3"
npm_rs = "1.0.0"
num-traits = "0.2"
pluralizer = "0.5.0"
poise = "0.7.0"
regex = "1.13.1"
reqwest = "0.12.28"
rootcause = "0.13.0"
rootcause-tracing = "0.13.0"
rustc-hash = "2.1.0"
serde = "1"
serde_json = "1"
sqlx = { version = "0.9.0", features = ["runtime-tokio", "sqlite", "migrate"] }
tempfile = "3"
tokio = { version = "1", default-features = false }
tokio-cron-scheduler = "0.15.1"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
twemoji-assets = "1"
url = "2"
walkdir = "2"
zip = "8.6.0"

[workspace.metadata.release]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
# strip = true
opt-level = 3
lto = true
codegen-units = 1

[profile.dev.package.sqlx-macros]
opt-level = 3
