[workspace]
resolver = "2"
members = [
    "utils",
    "archival",
    "eh_bot",
    "wiper",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
# strip = true
opt-level = 3
lto = true
codegen-units = 1
