[package]
name = "wiper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poise = "0.5.5"
poise_macros = "0.5.5"
anyhow = "1.0.72"
futures = "0.3.28"
utils = { path = "../utils" }
chrono = "0.4.26"