[package]
name = "eh_bot"
version = "0.3.2"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
archival = { path = "../archival" }
camino = { workspace = true }
chrono = { workspace = true }
fs-err = { workspace = true }
indexmap = "2.14.2"
poise = { workspace = true }
reminders = { path = "../reminders" }
rootcause = { workspace = true }
rootcause-tracing = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
tokio-cron-scheduler = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
utils = { path = "../utils" }
