on:
  push:
    # types: [created]

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          # - release_for: Linux-x86_64
          #   os: ubuntu-20.04
          #   target: x86_64-unknown-linux-musl
          #   bin: eh_bot
          #   name: eh_bot-x86_64.tar.gz
          #   command: build

          - release_for: Linux-ARMv7-gnu-hf
            os: ubuntu-20.04
            target: armv7-unknown-linux-gnueabihf
            bin: eh_bot
            name: eh_bot-ARMv7.tar.gz
            command: build

          # - release_for: Windows-x86_64
          #   os: windows-latest
          #   target: x86_64-pc-windows-msvc
          #   bin: eh_bot.exe
          #   name: eh_bot-Windows-x86_64.zip
          #   command: both

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: "ls"
      - name: "Install packages"
        run: "npm ci"
        working-directory: archival/archive_viewer
      - name: "Build nodejs"
        run: "npm run build-ci"
        working-directory: archival/archive_viewer
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "ci-test-rust"
          key: ${{ matrix.platform.release_for }}
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - run: "find . -name ${{ matrix.platform.name }}"
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.platform.target }}/release/${{ matrix.platform.name }}
          asset_name: ${{ matrix.platform.name }}
          # tag: ${{ github.ref }}
          tag: "v0.0.1"

    # more packaging stuff goes here ...
